<?php
declare(strict_types=1);
$editingProduct = $editingProduct ?? null;
$v = static fn (string $key, string $default = ''): string => htmlspecialchars((string) ($editingProduct[$key] ?? $default), ENT_QUOTES, 'UTF-8');
?>
<div class="container py-4">
    <div class="d-flex justify-content-between align-items-center gap-3 mb-4"><div><p class="text-primary fw-semibold mb-1">Ventas</p><h1 class="h2 mb-0">Productos</h1></div><a class="btn btn-outline-secondary" href="<?= htmlspecialchars($url->to('/vendedor'), ENT_QUOTES, 'UTF-8') ?>">Volver</a></div>
    <div class="row g-4">
        <div class="col-12 col-xl-5"><section class="bento-card p-4"><h2 class="h4"><?= $editingProduct ? 'Modificar producto' : 'Nuevo producto' ?></h2>
            <p class="text-muted">El stock se controla exclusivamente desde Almacén. Los productos nuevos comienzan en cero.</p>
            <form method="post" enctype="multipart/form-data" action="<?= htmlspecialchars($url->to($editingProduct ? '/vendedor/productos/' . $editingProduct['id_producto'] : '/vendedor/productos'), ENT_QUOTES, 'UTF-8') ?>" class="row g-3">
                <input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrfToken, ENT_QUOTES, 'UTF-8') ?>">
                <div class="col-md-5"><label class="form-label">Código</label><input class="form-control" name="codigo" maxlength="50" required value="<?= $v('codigo') ?>"></div><div class="col-md-7"><label class="form-label">Nombre</label><input class="form-control" name="nombre" maxlength="200" required value="<?= $v('nombre') ?>"></div>
                <div class="col-12"><label class="form-label">Descripción</label><textarea class="form-control" name="descripcion" rows="2" maxlength="5000"><?= $v('descripcion') ?></textarea></div>
                <div class="col-md-6"><label class="form-label">Modelo</label><input class="form-control" name="modelo" maxlength="100" value="<?= $v('modelo') ?>"></div><div class="col-md-6"><label class="form-label">Unidad</label><input class="form-control" name="unidad_medida" maxlength="30" value="<?= $v('unidad_medida', 'UNIDAD') ?>"></div>
                <div class="col-md-4"><label class="form-label">Categoría</label><select class="form-select" name="id_categoria" required><option value="">Selecciona</option><?php foreach ($relations['categories'] as $item): ?><option value="<?= (int) $item['id_categoria'] ?>" <?= (int) ($editingProduct['id_categoria'] ?? 0) === (int) $item['id_categoria'] ? 'selected' : '' ?>><?= htmlspecialchars($item['nombre'], ENT_QUOTES, 'UTF-8') ?></option><?php endforeach; ?></select></div>
                <div class="col-md-4"><label class="form-label">Marca</label><select class="form-select" name="id_marca"><option value="">Sin marca</option><?php foreach ($relations['brands'] as $item): ?><option value="<?= (int) $item['id_marca'] ?>" <?= (int) ($editingProduct['id_marca'] ?? 0) === (int) $item['id_marca'] ? 'selected' : '' ?>><?= htmlspecialchars($item['nombre'], ENT_QUOTES, 'UTF-8') ?></option><?php endforeach; ?></select></div>
                <div class="col-md-4"><label class="form-label">Proveedor</label><select class="form-select" name="id_proveedor"><option value="">Sin proveedor</option><?php foreach ($relations['suppliers'] as $item): ?><option value="<?= (int) $item['id_proveedor'] ?>" <?= (int) ($editingProduct['id_proveedor'] ?? 0) === (int) $item['id_proveedor'] ? 'selected' : '' ?>><?= htmlspecialchars($item['nombre'], ENT_QUOTES, 'UTF-8') ?></option><?php endforeach; ?></select></div>
                <div class="col-md-6"><label class="form-label">Precio compra (Bs)</label><input class="form-control" type="number" name="precio_compra" min="0" step="0.01" required value="<?= $v('precio_compra', '0.00') ?>"></div><div class="col-md-6"><label class="form-label">Precio venta (Bs)</label><input class="form-control" type="number" name="precio_venta" min="0" step="0.01" required value="<?= $v('precio_venta', '0.00') ?>"></div>
                <div class="col-md-4"><label class="form-label">Stock mínimo</label><input class="form-control" type="number" name="stock_minimo" min="0" required value="<?= $v('stock_minimo', '5') ?>"></div><div class="col-md-4"><label class="form-label">Stock máximo</label><input class="form-control" type="number" name="stock_maximo" min="0" required value="<?= $v('stock_maximo', '100') ?>"></div><div class="col-md-4"><label class="form-label">Estado</label><select class="form-select" name="estado"><option value="activo" <?= ($editingProduct['estado'] ?? 'activo') === 'activo' ? 'selected' : '' ?>>Activo</option><option value="inactivo" <?= ($editingProduct['estado'] ?? '') === 'inactivo' ? 'selected' : '' ?>>Inactivo</option></select></div>
                <div class="col-md-7"><label class="form-label">Ubicación</label><input class="form-control" name="ubicacion" maxlength="100" value="<?= $v('ubicacion') ?>"></div><div class="col-md-5"><label class="form-label">Imagen WebP</label><input class="form-control" type="file" name="imagen" accept="image/webp"></div>
                <div class="col-12 d-flex gap-2"><button class="btn btn-primary" type="submit"><?= $editingProduct ? 'Guardar cambios' : 'Crear producto' ?></button><?php if ($editingProduct): ?><a class="btn btn-outline-secondary" href="<?= htmlspecialchars($url->to('/vendedor/productos'), ENT_QUOTES, 'UTF-8') ?>">Cancelar</a><?php endif; ?></div>
            </form>
        </section></div>
        <div class="col-12 col-xl-7"><section class="bento-card p-4"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Producto</th><th>Precio</th><th>Stock</th><th>Estado</th><th></th></tr></thead><tbody><?php foreach ($products as $product): ?><tr><td><strong><?= htmlspecialchars($product['nombre'], ENT_QUOTES, 'UTF-8') ?></strong><br><small><?= htmlspecialchars($product['codigo'] . ' · ' . $product['categoria'], ENT_QUOTES, 'UTF-8') ?></small></td><td>Bs <?= number_format((float) $product['precio_venta'], 2) ?></td><td><?= (int) $product['stock_actual'] ?></td><td><?= htmlspecialchars($product['estado'], ENT_QUOTES, 'UTF-8') ?></td><td><a class="btn btn-sm btn-outline-primary" href="<?= htmlspecialchars($url->to('/vendedor/productos/' . $product['id_producto'] . '/editar'), ENT_QUOTES, 'UTF-8') ?>">Editar</a></td></tr><?php endforeach; ?></tbody></table></div></section></div>
    </div>
</div>
