<?php
declare(strict_types=1);
$base = $sellerMode ? '/vendedor/carrito' : '/carrito';
$total = array_reduce($items, static fn (float $sum, array $item): float => $sum + (float) $item['subtotal'], 0.0);
?>
<div class="container py-4">
    <div class="d-flex justify-content-between align-items-center mb-4"><div><p class="text-primary fw-semibold mb-1"><?= $sellerMode ? 'Ventas' : 'Cliente' ?></p><h1 class="h2 mb-0"><?= $sellerMode ? 'Venta asistida' : 'Mi carrito' ?></h1></div><a class="btn btn-outline-secondary" href="<?= htmlspecialchars($url->to($sellerMode ? '/vendedor' : '/catalogo'), ENT_QUOTES, 'UTF-8') ?>">Volver</a></div>
    <div class="row g-4">
        <div class="col-12 col-lg-4"><section class="bento-card p-4"><h2 class="h4">Agregar producto</h2><form method="post" action="<?= htmlspecialchars($url->to($base . '/agregar'), ENT_QUOTES, 'UTF-8') ?>" class="row g-3"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrfToken, ENT_QUOTES, 'UTF-8') ?>"><div class="col-12"><select class="form-select" name="id_producto" required><option value="">Selecciona</option><?php foreach ($products as $product): ?><option value="<?= (int) $product['id_producto'] ?>"><?= htmlspecialchars($product['codigo'] . ' · ' . $product['nombre'] . ' · Bs ' . number_format((float) $product['precio_venta'], 2) . ' · stock ' . $product['stock_actual'], ENT_QUOTES, 'UTF-8') ?></option><?php endforeach; ?></select></div><div class="col-5"><input class="form-control" name="cantidad" type="number" min="1" value="1" required></div><div class="col-7"><button class="btn btn-primary w-100" type="submit">Agregar</button></div></form></section></div>
        <div class="col-12 col-lg-8"><section class="bento-card p-4"><h2 class="h4">Contenido</h2><?php if ($items === []): ?><p class="text-muted mb-0">El carrito está vacío.</p><?php else: ?><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Producto</th><th>Precio</th><th>Cantidad</th><th>Subtotal</th><th></th></tr></thead><tbody><?php foreach ($items as $item): ?><tr><td><?= htmlspecialchars($item['codigo'] . ' · ' . $item['nombre'], ENT_QUOTES, 'UTF-8') ?></td><td>Bs <?= number_format((float) $item['precio_venta'], 2) ?></td><td><form class="d-flex gap-2" method="post" action="<?= htmlspecialchars($url->to($base . '/' . $item['id_producto']), ENT_QUOTES, 'UTF-8') ?>"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrfToken, ENT_QUOTES, 'UTF-8') ?>"><input class="form-control form-control-sm" style="width:5rem" type="number" min="0" max="<?= (int) $item['stock_actual'] ?>" name="cantidad" value="<?= (int) $item['cantidad'] ?>"><button class="btn btn-sm btn-outline-primary">Guardar</button></form></td><td>Bs <?= number_format((float) $item['subtotal'], 2) ?></td><td><form method="post" action="<?= htmlspecialchars($url->to($base . '/' . $item['id_producto'] . '/eliminar'), ENT_QUOTES, 'UTF-8') ?>"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrfToken, ENT_QUOTES, 'UTF-8') ?>"><button class="btn btn-sm btn-outline-danger">Quitar</button></form></td></tr><?php endforeach; ?></tbody><tfoot><tr><th colspan="3">Total</th><th>Bs <?= number_format($total, 2) ?></th><th></th></tr></tfoot></table></div><?php endif; ?></section></div>
        <?php if ($items !== []): ?><div class="col-12"><section class="bento-card p-4"><h2 class="h4">Confirmar operación</h2><form method="post" action="<?= htmlspecialchars($url->to($base . '/confirmar'), ENT_QUOTES, 'UTF-8') ?>" class="row g-3 align-items-end"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrfToken, ENT_QUOTES, 'UTF-8') ?>"><input type="hidden" name="checkout_token" value="<?= htmlspecialchars($checkoutToken, ENT_QUOTES, 'UTF-8') ?>"><?php if ($sellerMode): ?><div class="col-md-5"><label class="form-label">Cliente</label><select class="form-select" name="id_cliente" required><option value="">Selecciona</option><?php foreach ($clients as $client): ?><option value="<?= (int) $client['id_cliente'] ?>"><?= htmlspecialchars($client['nombre'] . ($client['numero_documento'] ? ' · ' . $client['numero_documento'] : ''), ENT_QUOTES, 'UTF-8') ?></option><?php endforeach; ?></select></div><?php endif; ?><div class="col-md-4"><label class="form-label">Entrega</label><select class="form-select" name="id_metodo_entrega" required><?php foreach ($deliveryMethods as $method): ?><option value="<?= (int) $method['id_metodo_entrega'] ?>"><?= htmlspecialchars($method['nombre'], ENT_QUOTES, 'UTF-8') ?></option><?php endforeach; ?></select></div><div class="col-md-3"><button class="btn btn-primary w-100" type="submit">Confirmar Bs <?= number_format($total, 2) ?></button></div></form></section></div><?php endif; ?>
    </div>
</div>
