<?php declare(strict_types=1); ?>
<div class="container py-4">
    <div class="d-flex flex-wrap justify-content-between align-items-center mb-4"><div><p class="text-primary fw-semibold mb-1">Rol <?= htmlspecialchars($user['role'], ENT_QUOTES, 'UTF-8') ?></p><h1 class="h2">Inventario y trazabilidad</h1><p>Registra entradas, salidas o ajustes. En un ajuste, la cantidad representa el stock final.</p></div><a class="btn btn-primary" href="<?= htmlspecialchars($url->to('/almacen/envios'), ENT_QUOTES, 'UTF-8') ?>">Gestionar despachos</a></div>
    <div class="row g-4">
        <div class="col-12 col-lg-4"><section class="bento-card p-4"><h2 class="h4">Nuevo movimiento</h2><form method="post" action="<?= htmlspecialchars($url->to('/almacen/movimientos'), ENT_QUOTES, 'UTF-8') ?>" class="row g-3"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrfToken, ENT_QUOTES, 'UTF-8') ?>"><div class="col-12"><label class="form-label">Producto</label><select class="form-select" name="id_producto" required><option value="">Selecciona</option><?php foreach ($products as $product): ?><option value="<?= (int) $product['id_producto'] ?>"><?= htmlspecialchars($product['codigo'] . ' · ' . $product['nombre'] . ' (stock ' . $product['stock_actual'] . ')', ENT_QUOTES, 'UTF-8') ?></option><?php endforeach; ?></select></div><div class="col-md-6"><label class="form-label">Tipo</label><select class="form-select" name="tipo_movimiento"><option>ENTRADA</option><option>SALIDA</option><option>AJUSTE</option></select></div><div class="col-md-6"><label class="form-label">Cantidad / stock final</label><input class="form-control" type="number" min="0" name="cantidad" required></div><div class="col-12"><label class="form-label">Motivo</label><textarea class="form-control" name="motivo" maxlength="500" required></textarea></div><div class="col-12"><button class="btn btn-primary" type="submit">Registrar movimiento</button></div></form></section></div>
        <div class="col-12 col-lg-8"><section class="bento-card p-4"><h2 class="h4">Existencias</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Producto</th><th>Ubicación</th><th>Stock</th><th>Límites</th></tr></thead><tbody><?php foreach ($products as $product): ?><tr><td><strong><?= htmlspecialchars($product['nombre'], ENT_QUOTES, 'UTF-8') ?></strong><br><small><?= htmlspecialchars($product['codigo'], ENT_QUOTES, 'UTF-8') ?></small></td><td><?= htmlspecialchars($product['ubicacion'] ?? 'Sin ubicación', ENT_QUOTES, 'UTF-8') ?></td><td><span class="badge text-bg-<?= (int) $product['stock_actual'] <= (int) $product['stock_minimo'] ? 'warning' : 'success' ?>"><?= (int) $product['stock_actual'] ?></span></td><td><?= (int) $product['stock_minimo'] ?>–<?= (int) $product['stock_maximo'] ?></td></tr><?php endforeach; ?></tbody></table></div></section></div>
        <div class="col-12"><section class="bento-card p-4"><h2 class="h4">Últimos movimientos</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Fecha</th><th>Producto</th><th>Tipo</th><th>Cambio</th><th>Stock</th><th>Responsable y motivo</th></tr></thead><tbody><?php foreach ($movements as $movement): ?><tr><td><?= htmlspecialchars($movement['fecha_movimiento'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($movement['codigo'] . ' · ' . $movement['producto'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($movement['tipo_movimiento'], ENT_QUOTES, 'UTF-8') ?></td><td><?= (int) $movement['cantidad'] ?></td><td><?= (int) $movement['stock_anterior'] ?> → <?= (int) $movement['stock_nuevo'] ?></td><td><?= htmlspecialchars($movement['usuario'] . ' · ' . ($movement['observacion'] ?? ''), ENT_QUOTES, 'UTF-8') ?></td></tr><?php endforeach; ?></tbody></table></div></section></div>
        <div class="col-12"><section class="bento-card p-4"><h2 class="h4">Compras pendientes de recepción</h2><?php if ($pendingPurchases === []): ?><p class="mb-0">No hay compras pendientes.</p><?php else: ?><div class="table-responsive"><table class="table"><thead><tr><th>Compra</th><th>Proveedor</th><th>Total</th><th>Recepción</th></tr></thead><tbody><?php foreach ($pendingPurchases as $purchase): ?><tr><td>#<?= (int) $purchase['id_compra'] ?> · <?= htmlspecialchars($purchase['fecha_compra'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($purchase['proveedor'], ENT_QUOTES, 'UTF-8') ?></td><td>Bs <?= number_format((float) $purchase['total'], 2) ?></td><td><form method="post" action="<?= htmlspecialchars($url->to('/almacen/compras/' . $purchase['id_compra'] . '/recibir'), ENT_QUOTES, 'UTF-8') ?>" class="d-flex gap-2"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrfToken, ENT_QUOTES, 'UTF-8') ?>"><input class="form-control form-control-sm" name="motivo" maxlength="500" required placeholder="Motivo/recepción"><button class="btn btn-sm btn-primary">Recibir</button></form></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section></div>
    </div>
</div>
